title: Résumé de OpenAPI
source:
  - https://github.com/OAI/OpenAPI-Specification
  - https://www.openapis.org/
  - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md
  
doc: |

  Tags MUST be limited to those allowed by the JSON Schema ruleset.
  Keys used in YAML maps MUST be limited to a scalar string, as defined by the YAML Failsafe schema ruleset.
  
  An OpenAPI document MAY be made up of a single document or be divided into multiple, connected parts at the discretion of the user. In the latter case, $ref fields MUST be used in the specification to reference those parts as follows from the [JSON Schema](http://json-schema.org/) definitions.